### ISSUE TITLE
Server dont starting

### ISSUE THREAD

**Issue by pepters** [Tee1er/boing#14]
root@pk020311:~/boing# ./run.sh
Checking / installing dependencies.
Installing dependencies. This may take a while.
npm WARN deprecated @discordjs/collection@0.1.6: no longer supported
npm WARN deprecated @sapphire/snowflake@1.3.6: This version has been automatically deprecated by @favware/npm-deprecate. Please use a newer version.
npm WARN deprecated @discordjs/rest@0.1.0-canary.0: no longer supported
npm WARN deprecated discord-api-types@0.18.1: No longer supported. Install the latest release (0.20.2)
npm WARN deprecated discord-api-types@0.23.1: No longer supported. Install the latest release!

added 152 packages, and audited 153 packages in 8s

32 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/root/boing/boing/src/globals.js:33
        throw new Error("Failed to retrieve settings.");
        ^

Error: Failed to retrieve settings.
    at loadSettings (/root/boing/boing/src/globals.js:33:15)
    at Object.<anonymous> (/root/boing/boing/src/launcher.js:18:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
root@pk020311:~/boing#

**Comment by ebears** [comment]
You need to create a new settings file: `boing/data/settings.json`. As long as the file is enclosed in curly brackets, it should generate settings during the setup. To be clear, once you create `settings.json`, it should look like this:
```
{}
```
